app:
  base_working_dir: /tmp/ddat-parser
  webdriver_paths:
    chromedriver: /opt/drivers/webdrivers/chromedriver/117.0.5938.92/chromedriver
  visualisation:
    apply_filters: true
ddat:
  base_url: https://ddat-capability-framework.service.gov.uk
  resources:
    skills: skills.html